### PR TITLE
L1-EP Restoration method

### PR DESCRIPTION
**Pull request by dthierry**
Updated with a new restoration alternative.
Details listed in the `README.md`.

### CODE REVIEW

**Comment by dthierry** [comment]
@eslickj can we resolve the conflicts?, I can do it, if you give me the permissions.

**Comment by eslickj** [comment]
@dthierry, I think you are added.  Let me know if you have trouble.

**Review by dthierry — COMMENTED** [review]
HSL loader might need some attention.

**Comment by dthierry** [comment]
@eslickj Now that the branch has been merged, should we run some tests? Thanks.

**Comment by eslickj** [comment]
@dthierry, sure I'll try to build it along with the rest of the solvers.  Should be pretty straight forward.  What should we call the solver executable?

**Comment by dthierry** [comment]
Thanks @eslickj, let's say `ipopt_l1`.

**Pull request merged**
